// <auto-generated />
using System;
using ECommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20251117232527_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Customer_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Customer_Email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Customer_Name");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Customer_Phone");

                    b.HasKey("CustomerID");

                    b.HasIndex("CustomerEmail")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            CustomerEmail = "nada@example.com",
                            CustomerName = "Nada Assem",
                            CustomerPhone = "0123456789"
                        },
                        new
                        {
                            CustomerID = 2,
                            CustomerEmail = "ali@example.com",
                            CustomerName = "Ali Mohamed",
                            CustomerPhone = "0112233445"
                        },
                        new
                        {
                            CustomerID = 3,
                            CustomerEmail = "sara@example.com",
                            CustomerName = "Sara Khaled",
                            CustomerPhone = "0109988776"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Order_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int")
                        .HasColumnName("Customer_ID");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Order_Date");

                    b.Property<int>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("Status_ID");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total_Price");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("StatusID");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderItem_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int")
                        .HasColumnName("Order_ID");

                    b.Property<int>("ProductID")
                        .HasColumnType("int")
                        .HasColumnName("Product_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Unit_Price");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Status_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status_Name");

                    b.HasKey("StatusID");

                    b.ToTable("OrderStatus", (string)null);

                    b.HasData(
                        new
                        {
                            StatusID = 1,
                            StatusName = "Pending"
                        },
                        new
                        {
                            StatusID = 2,
                            StatusName = "Processing"
                        },
                        new
                        {
                            StatusID = 3,
                            StatusName = "Completed"
                        },
                        new
                        {
                            StatusID = 4,
                            StatusName = "Cancelled"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Product_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Product_Description");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Product_Name");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Product_Price");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            ProductDescription = "High performance laptop",
                            ProductName = "Laptop",
                            ProductPrice = 15000m,
                            Stock = 12
                        },
                        new
                        {
                            ProductID = 2,
                            ProductDescription = "Flagship smartphone",
                            ProductName = "Smartphone",
                            ProductPrice = 11000m,
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 3,
                            ProductDescription = "Noise canceling",
                            ProductName = "Wireless Headphones",
                            ProductPrice = 3200m,
                            Stock = 45
                        },
                        new
                        {
                            ProductID = 4,
                            ProductDescription = "Water resistant",
                            ProductName = "Smartwatch",
                            ProductPrice = 2800m,
                            Stock = 20
                        },
                        new
                        {
                            ProductID = 5,
                            ProductDescription = "Portable speaker",
                            ProductName = "Bluetooth Speaker",
                            ProductPrice = 1500m,
                            Stock = 50
                        },
                        new
                        {
                            ProductID = 6,
                            ProductDescription = "RGB keyboard",
                            ProductName = "Gaming Keyboard",
                            ProductPrice = 900m,
                            Stock = 35
                        },
                        new
                        {
                            ProductID = 7,
                            ProductDescription = "High DPI mouse",
                            ProductName = "Gaming Mouse",
                            ProductPrice = 700m,
                            Stock = 40
                        },
                        new
                        {
                            ProductID = 8,
                            ProductDescription = "Android tablet",
                            ProductName = "Tablet 10 inch",
                            ProductPrice = 6000m,
                            Stock = 18
                        },
                        new
                        {
                            ProductID = 9,
                            ProductDescription = "USB 3.0",
                            ProductName = "External Hard Disk 1TB",
                            ProductPrice = 1900m,
                            Stock = 25
                        },
                        new
                        {
                            ProductID = 10,
                            ProductDescription = "4K UHD",
                            ProductName = "TV 55 inch",
                            ProductPrice = 18000m,
                            Stock = 10
                        },
                        new
                        {
                            ProductID = 11,
                            ProductDescription = "High speed router",
                            ProductName = "Router WiFi 6",
                            ProductPrice = 2500m,
                            Stock = 22
                        },
                        new
                        {
                            ProductID = 12,
                            ProductDescription = "Fast charging",
                            ProductName = "Power Bank 20000mAh",
                            ProductPrice = 800m,
                            Stock = 60
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
